lanauage: go
go:
  - master

cache:
  yarn: true
  directories:
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build
    - packages/ga/node_modules

before_install:
  - nvm install 10

install:
  - go mod download
  - pushd packages/ga && yarn install && popd

script:
  - make
  - pushd packages/ga
  - yarn test
  - yarn build
  - yarn size
  - popd